[project]
name = "omnipy-examples"
version = "0.8.0"
description = ""
authors = [{name="Sveinung Gundersen"} , {name="Jeanne Cheneby"}]
maintainers = [{name="Sveinung Gundersen"}]
readme = "README.md"
requires-python = ">=3.10,<3.14"
packages = [{include = "omnipy_examples", from = "src"}]
include = [
    { path = "input" }
]
dependencies = [
    "omnipy-example-data (>=0.1.0)",
    "reader (>=3.4)",
    "omnipy (>=0.23.1)",
    "boto3 (>=1.35.23)",
    "prefect (>=2.13.2,<3)",
    "typing-extensions (>=4.12.2,<5)",
    "python-slugify (>=8.0.4,<9)",
    "jsoncanon (>=0.2.3)",
    "cyclopts>=4.11.0",
    "basedpyright>=1.39.3",
    "pydantic[email]<2",
    "bionumpy (>=1.0.14,<2.0.0)",
]

[dependency-groups]
dev = [
    "pre-commit (>=3.8.0)",
    "mypy (>=1.11.2)",
    "basedpyright>=1.39.3",
]

[project.scripts]
omnipy-examples = "omnipy_examples.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/omnipy"]

[tool.yapf]
allow_split_before_dict_value = true
based_on_style = "google"
align_closing_bracket_with_visual_indent = true
blank_line_before_nested_class_or_def = false
column_limit = 100
indent_dictionary_value = true
join_multiple_lines = true
split_all_comma_separated_values = false
split_all_top_level_comma_separated_values = true
split_before_expression_after_opening_paren = true
split_before_bitwise_operator = true
split_before_logical_operator = true
split_before_arithmetic_operator = true

[tool.isort]
profile = "google"
force_single_line = false
multi_line_output = 1
src_paths = ["src/examples", "tests"]
line_length = 100

[tool.mypy]
python_version = "3.10"
mypy_path = "src:tests"
warn_no_return = false
disable_error_code = ["valid-type", "empty-body"]

[tool.uv.sources]
omnipy = { path = "../omnipy" }

